"""empty message

Revision ID: c71afde7084c
Revises: be96bfe43744
Create Date: 2020-09-23 06:34:42.761281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71afde7084c'
down_revision = 'be96bfe43744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
